model:
    # arch: mv3_res50
    # arch: unet
    arch: deeplabv3_os16_MG_plus
data:
    dataset: HRS_SAR_seg
    train_split: train
    val_split: test
    img_rows: 512
    img_cols: 512
    path: dataset/SAR_Seg_3/band3
training:
#    train_iters: 300000
    train_epoch: 100
    batch_size: 16
    val_interval: 30
    n_workers: 16       # 6c12t in i7-6800k in apple
    print_interval: 10
    optimizer:
        name: 'adam'
        # lr: 1.0e-2
        lr: 5.0e-3
        # weight_decay: 0.0005
        # momentum: 0.99

    loss:
        name: 'cross_entropy'
        # name: 'focal_loss_2d'
        # alpha: 1
        # gamma: 1
        # reduction: 'mean'
    lr_schedule: 
        name: 'poly_lr_chen'
        max_iter: 5000
    # resume: runs/HRS_SAR_seg_chen/82684/deeplabv3_os16_MG_plus_HRS_SAR_seg_best_model.pkl
    resume: mv3_res50_my_best_model.pkl
