# data in polar coordinate
model:
    arch: surreal_siam_diff5
    input_nbr: 4
    drop_p: 0
    # channel_scale: 0.25
    # label_nbr: 2
data:
    dataloader: PolSAR_CD_base
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    format: polar_s2
    path: /data/csl/SAR_CD/GF3
    norm: False
train:
    augment: 
        'hflip': 0.5
        'vflip': 0.5
        # 'rotate': 180
    epoch: 100
    batch_size: 4
    val_interval: 30
    n_workers: 4
    print_interval: 10
    optimizer:
        # wrap: 'lars'
        name: 'adam'    
        # name: 'sgd'
        lr: 1.0e-3
        # lr: 5.0e-4
        weight_decay: 1.0e-5
        # momentum: 0.9
    lr: 
        name: 'constant_lr'
        # name: 'poly_lr_chen'
        # max_iter: 8000
    loss:
        name: 'cross_entropy_mask'
        weight: [0.02, 0.98]
        # name: 'focal_loss_2d'
        # alpha: 1
        # gamma: 1
        # reduction: 'mean'
    # resume: runs/siam-diff_cross_entropy_mask_sgd_poly_lr_chen_15//siam-diff_SAR_CD_intensity_best_model.pkl
    # resume: runs/fresunet_cross_entropy_mask_adam_constant_lr_1/fresunet_SAR_CD_intensity_last_model.pkl
    resume: 
    clip: False
test:
    out_path: 'result'
    pth: 'runs/surreal_siam_diff3_cross_entropy_mask_sgd_poly_lr_chen_0/surreal_siam_diff3_PolSAR_CD_base_best_model.pkl'
    gpu: [0]
    augments:
    batch_size: 8
    n_workers: 8
    dataset: 'test'