model:
    arch: resnet18_wo_BN
    in_channels: 6    
    num_classes: 2
data:
    dataloader: SAR_CD_tile_1
    train_split: train
    val_split: val
    tile_size: 64
    path: /home/csl/data/SAR_CD/RS2
train:
#    train_iters: 300000
    train_epoch: 1000
    batch_size: 128
    val_interval: 60
    n_workers: 32
    print_interval: 30
    optimizer:
        name: 'adam'
        # name: 'sgd'
        # lr: 1.0e-2
        lr: 5.0e-6
        # weight_decay: 0.0005
        # momentum: 0.99

    loss:
        name: 'cross_entropy'
        weight: [0.01, 2.0]
        # name: 'focal_loss_2d'
        # alpha: 1
        # gamma: 1
        # reduction: 'mean'
    lr_schedule: 
        name: 'constant_lr'
        # name: 'poly_lr_chen'
        # max_iter: 3200
    clip: False
    resume: 
test:
    pth:
    train_set: True
    val_set:  True